- name: Create a micro instance in AWS EC2
  hosts: localhost
  gather_facts: false
  vars:
    keypair: "Sinensia_ok"
    instance_type: t2.micro
    security_group: "launch-wizard-1"
    subnet_id: "subnet-0b7cf7c1dfd0a6dbd"
    image: ami-0d71ea30463e0ff8d
    region: eu-west-1
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        instance_tags:
          Name: docker-instance
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
      loop: "{{ ec2.instances }}"

- name: Configure instances
  hosts: launched
  become: true
  gather_facts: true
  vars:
    ansible_user: ec2-user

  tasks:
    - name: Install docker
      yum:
        name: docker

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose

    - name: Add the user
      user:
        name: ec2-user
        group: docker

    - name: symbolic link
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        mode: '0755'

    - name: Starting service docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Copy the application
      copy:
        src: /home/sinensia/vue-2048/docker-compose.yaml
        dest: /opt/docker/

    - name: docker-compose pull
      shell: docker-compose -f /opt/docker/docker-compose.yaml pull

    - name: docker-compose up
      shell: docker-compose -f /opt/docker/docker-compose.yaml up -d --no-build