---
- hosts: aws
  tasks:
    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: Start service
      command: systemctl start httpd
      become: yes


    - name: move a html
      copy:
        src: vue-2048/dist/
        dest: /var/www/html
      become: yes









