---
- hosts: docker
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd

    - name: Start service httpd
      service:
        name: httpd
        enabled: true
        state: started


    - name: Start service
      become: yes
      command: systemctl start httpd



    - name: Copy the application
      become: yes
      copy:
        src: vue-2048/dist/
        dest: /var/www/html










