---
- hosts: docker
  become: yes
  tasks:
    - name: Install docker
      yum:
        name: docker

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Starting service springtesting
      service:
        name: docker
        enabled: true
        state: started

    - name: Copy the application
      copy:
        src: /home/sinensia/vue-2048/docker-compose.yaml
        dest: /opt/docker/
        mode: '0755'

    - name:
      file:
        path: /var/run/docker.sock
        mode: '0777'

    - name:
      file:
        path: /var/lib/docker/
        mode: '0777'






